### ISSUE TITLE
Extension Manager fails to start extension after loading

### ISSUE THREAD

**Issue by redmunds** [iwehrman/brackets-csslint#1] opened 2013-09-18 19:40 UTC
Here's the error:

```
Failed to load resource file:///C:/Users/redmunds/AppData/Roaming/Brackets/extensions/user/brackets-csslint/thirdparty/csslint/release/csslint.js
[Extension] failed to load C:/Users/redmunds/AppData/Roaming/Brackets/extensions/user/brackets-csslint 
Error
get stack: function () { [native code] }
message: "Script error for: thirdparty/csslint/release/csslint↵http://requirejs.org/docs/errors.html#scripterror"
originalError: Event
requireModules: Array[1]
requireType: "scripterror"
set stack: function () { [native code] }
__proto__: d
 ExtensionLoader.js:167
```

It looks like you may be using a submodule. I don't think Extension Manager supports that, and it wasn't mentioned in the readme.

**Comment by redmunds** [comment] 2013-09-18 20:11
I forgot to mention that I tried installing from both the Brackets Extension Registry and using Install from URL. Above is the error message from Install from URL.

Seems like the .zip file uploaded to the Brackets Registry would have the csslint files as part of the package, so maybe that's a different error.

**Comment by iwehrman** [comment] 2013-09-19 00:03
Caused by adobe/brackets#5257. Resolved by removing the .git directory from the registry archive and by including CSSLint directly.

**Closed as completed by iwehrman** 2013-09-19 00:03 UTC
